### ISSUE TITLE
Events Not Delegated for Devices Supporting Touch & Click

### ISSUE THREAD

**Issue by epiales** [nervetattoo/backbone.touch#18]
Devices that support touch events **and** click events will not delegate click events, thereby not allowing certain elements to be clicked, only touched.

I've tested this on Chrome with my Acer Aspire S7 (Windows 8.1), Chrome on Mac OSX (10.9.4) as well as Safari on iPhone 5 (7.1). Mac and iPhone work as expected, however, the Acer is a touchscreen enabled laptop and when using this plugin, any click event that has been registered on an element prevents the handler from being called when clicking as normal, I can only touch the screen for the expected behavior.

similar problem to #13

**Comment by alexparker** [comment]
I've run into this same issue on windows 8.1 chrome when a touch monitor is plugged in.
